# coding: utf-8
from pylab import *

x = arange(-20, 20, 0.3)
plot(x+1, x, "-")
plot(x+2, x, "--")
plot(x+3, x, "-.")
plot(x+4, x, ":")
plot(x+5, x, ".")
plot(x+6, x, ",")
plot(x+7, x, "o")
plot(x+8, x, "^")
plot(x+9, x, "v")
plot(x+10, x, "<")
plot(x+11, x, ">")
plot(x+12, x, "s")
plot(x+13, x, "+")
plot(x+14, x, "x")
plot(x+15, x, "D")
plot(x+16, x, "d")
plot(x+17, x, "1")
plot(x+18, x, "2")
plot(x+19, x, "3")
plot(x+20, x, "4")
plot(x+21, x, "h")
plot(x+22, x, "H")
plot(x+23, x, "p")
plot(x+24, x, "|")
plot(x+25, x, "_")

legend(["-", "--", "-.", ":", ".", ",", "o", "^", "v", "<", ">", "s", "+", "x", "D", "d", "1", "2", "3", "4", "h", "H", "p", "|", "_"], numpoints=5, pad=0.1)

xlim(0, 30)
ylim(-5, 5)

show()
